// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQpyfDMuyNBcepsVFuZ9oawP4U9oZqRbQ',
    appId: '1:171196081341:android:fcebe041ad1e04a0fac3d4',
    messagingSenderId: '171196081341',
    projectId: 'ecotrack-63827',
    storageBucket: 'ecotrack-63827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
  apiKey: 'AIzaSyDoiM9CraGtADXrkS7NoAo0-QsG3AVQ278',
  appId: '1:171196081341:ios:e434930d5b073a48fac3d4',
  messagingSenderId: '171196081341',
  projectId: 'ecotrack-63827',
  storageBucket: 'ecotrack-63827.firebasestorage.app',
  iosBundleId: 'com.example.ecotrack', 
);
}

